sudo: false
language: go
go:
  - 1.4.2
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - PATH=$PATH:$HOME/gopath/bin
  - go get -v -t ./...
  - go get github.com/tools/godep
  - go get github.com/apcera/gnatsd
  - godep restore
script:
  - go tool vet -composites=false $(ls -d */ | grep -v Godeps)
  - ginkgo -r -race -failOnPending -randomizeAllSpecs
branches:
  only:
  - master
